Extend AbstractStringContainer for compatibility with ToC, etc.
8fold/commonmark-abbreviations pull request #8
Opened 2021-05-01 21:52 UTC by Ambient-Impact

thephpleague/commonmark@b6b080a974a5f654fd2664a8f74a6e0ca156d461 fixed unparsed inline Markdown ending up in the table of contents (yay!) but seems to have caused abbreviations to be totally stripped from the table of contents (less yay) due to said fix checking if any elements it finds are an ```AbstractStringContainer```, and since ```Abbreviation``` does not extend ```AbstractStringContainer```, the table of contents just chucks it out rather than outputting the plain text contents. This pull request fixes that problem by extending ```AbstractStringContainer``` so that CommonMark core (and potentially other extensions) see abbreviations as standard string containers with the expected methods for getting and setting content.

2021-05-02 12:14 UTC, joshbruce commented
Very cool - integrating more with the way CommonMark works.

I actually appreciate that abbreviations don't wind up in the TOC - mostly because of where I'm hoping abbreviations will be used - the body copy: 

- https://www.plainlanguage.gov/guidelines/words/minimize-abbreviations/

Given the specific callout of TOC - can we get a test showing the expected/desired usage?? (I tend to view tests as documentation for users as much as anything - helps reduce the need for other documentation. lol)

2021-05-02 22:01 UTC, Ambient-Impact commented
I definitely agree in the sense that we don't want the abbreviation markup in the generated table of contents, so outputting the plain text without the abbreviation is the goal.

I'll put together a test when I get a chance.

2021-05-02 22:18 UTC, joshbruce commented
Ah! That was the part I wasn't tracking on. You're definitely going deeper with CommonMark than my understanding and didn't catch that.

Thanks for the test in the future.

I could see a benefit of repeating the abbreviations all over in that use case...especially if sections are a bit longer.

Seems like a very interesting project. And congratulations on being funded!

2021-05-02 22:26 UTC, Ambient-Impact commented
> Ah! That was the part I wasn't tracking on (plain text fully spelled out). You're definitely going deeper with CommonMark than my understanding and didn't catch that.

It's certainly been a learning experience, let me tell you. :P Also mentioned this pull request in a related issue with heading permalinks stripping out the abbreviation plain text as well, so this is turning out to be a multi-layered thing.

> Seems like a very interesting project. And congratulations on being funded!

Thanks! It's been a long road, but we're getting close to ready for 1.0.

2021-05-02 22:56 UTC, Ambient-Impact commented
Let me know how that test looks to you and if it needs any changes.

2021-05-07 12:43 UTC, Ambient-Impact commented
(attempts to summon @joshbruce with a spell)

2021-05-07 13:13 UTC, joshbruce commented
Summons received. lol

What's up??

2021-05-07 14:11 UTC, Ambient-Impact commented
I humbly request thine review.

2021-05-07 14:21 UTC, joshbruce requested changes

2021-05-07 14:22 UTC, joshbruce commented
Apologies, thought my review notes were submitted. Just have the one at present.

2021-05-08 15:34 UTC, Ambient-Impact commented on tests/short-doc-abstract-string-container.html
> +<p><a href="#the">The USWDS</a></p>
You're right, that should be more descriptive. That's actually a problem with CommonMark that I uncovered while implementing this and opened an issue; see  thephpleague/commonmark#615

2021-05-08 19:53 UTC, joshbruce commented on tests/short-doc-abstract-string-container.html
> +<p><a href="#the">The USWDS</a></p>
Beyond the non-descriptive thing, I would presume all headers that start with the same word ("the" in this instance) would end up creating duplicate IDs; thereby, making the anchors not actually work.

It would be one thing if a user created multiple headers with the same content and not realizing the implications it could have on the HTML but this would be us doing it. Want to wait for it be the expected behavior before merging and releasing another update.

And it looks like @colinodell posted an update to the issue because he's awesome. :)

2021-05-08 20:01 UTC, joshbruce commented on tests/short-doc-abstract-string-container.html
> +<p><a href="#the">The USWDS</a></p>
To be clear, you're both awesome.

2021-05-09 15:52 UTC, Ambient-Impact commented on tests/short-doc-abstract-string-container.html
> +<p><a href="#the">The USWDS</a></p>
> Beyond the non-descriptive thing, I would presume all headers that start with the same word ("the" in this instance) would end up creating duplicate IDs; thereby, making the anchors not actually work.

The heading permalink extension actually [includes logic to ensure that IDs are unique](https://github.com/thephpleague/commonmark/blob/d70e575fc970ee050446883c2a75e48b7962d9b4/src/Extension/HeadingPermalink/HeadingPermalinkProcessor.php#L129), and so at least in the technical sense, it'll work even if a bunch of IDs are just "the", as they'll be turned into "the", "the1", "the2", and so on. Obviously, it's bad semantically and descriptively, but it shouldn't break anything.

> It would be one thing if a user created multiple headers with the same content and not realizing the implications it could have on the HTML but this would be us doing it. Want to wait for it to be the desired behavior before merging and releasing another update.

Now that league/commonmark 1.6.1 is out fixing this, and I've pushed an updated test, does that change your assessment?

2021-05-09 17:13 UTC, colinodell commented on tests/short-doc-abstract-string-container.html
> +<p><a href="#the">The USWDS</a></p>
> The heading permalink extension actually includes logic to ensure that IDs are unique

I'm considering enhancing this in 2.0 to ensure that any extension is able to generate a unique slug/ID that is guaranteed to not conflict with slugs/IDs generated by other extensions: https://github.com/thephpleague/commonmark/pull/617  I don't know if that has anything to do with your thoughts/concerns here but wanted to share this potential upcoming change just in case :)

2021-05-09 19:12 UTC, joshbruce commented on tests/short-doc-abstract-string-container.html
> +<p><a href="#the">The USWDS</a></p>
@colinodell: Left a comment. It could be helpful. Duplicating IDs is something I'm okay with as long as it's user error - it's just when library makes it happen where my brain freaks out. lol Would be curious how performance is affected from a small document compared to a large document.

 @Ambient-Impact: Yep, looks good. Might have to come back later today or Monday - was just in the area and didn't want to forget to comment. :)

2021-05-09 19:12 UTC, joshbruce approved these changes

2021-05-11 00:23 UTC, merged